version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: travel-mongodb
    ports:
      - "27017:27017"

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/travel
